version: "3.9"
services:
  postgres:
    image: "postgres:14"
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  redis:
    image: "redis:7"
    ports:
      - "6379:6379"
    volumes:
      - "./redis:/var/lib/redis/data"

volumes:
  postgres:
  redis:
